apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: bidrag
  name: {{ name }}
  namespace: bidrag
spec:
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
      outbound:
        external:
          - host: {{ access.outbound.oppgave }}
          - host: {{ access.outbound.bidrag-sak }}
  envFrom:
    - secret: test-auth-z992903
    - secret: bidrag-cucumber-cloud-secrets
  image: {{ image }}
  kafka:
    pool: nav-dev
  liveness:
    path: /bidrag-cucumber-cloud/actuator/health
    initialDelay: 35
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /bidrag-cucumber-cloud/actuator/health
    initialDelay: 30
    timeout: 1
  prometheus:
    enabled: true
    path: /bidrag-cucumber-cloud/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  env:
    - name: TOPIC_JOURNALPOST
      value: {{ kafka-topic-journalpost }}
    - name: OPPGAVE_SCOPE
      value: {{ scope.oppgave }}
    - name: SAK_SCOPE
      value: {{ scope.sak }}
    - name: BEREGN_SAERTILSKUDD_SCOPE
      value: {{ scope.beregn_saertilskudd }}
    - name: BEREGN_FORSKUDD_SCOPE
      value: {{ scope.beregn_forskudd }}
    - name: BEREGN_BARNEBIDRAG_SCOPE
      value: {{ scope.beregn_barnebidrag }}
    - name: DOKUMENT_FORSENDELSE_SCOPE
      value: {{ scope.dokument_forsendelse }}
    - name: BIDRAG_DOKUMENT_SCOPE
      value: {{ scope.bidrag_dokument }}
    - name: BIDRAG_VEDTAK_SCOPE
      value: {{ scope.bidrag_vedtak }}
    - name: BIDRAG_GRUNNLAG_SCOPE
      value: {{ scope.bidrag_grunnlag }}
    - name: BIDRAG_STONAD_SCOPE
      value: {{ scope.bidrag_stonad }}