apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: bidrag
  name: {{ name }}
  namespace: bidrag
spec:
  image: {{ image }}
  schedule: "30 3 * * *"
  template:
    spec:
      containers:
        - name: {{ name }}
          image: {{ image }}
          command: |
            [
              "mvn", "-f /pom.xml", "-Dexec.classpathScope=test", "-Dexec.mainClass=io.cucumber.core.cli.Main"
              "-Dexec.args="src/test/resources/no/nav/bidrag/cucumber/cloud --glue no.nav.bidrag.cucumber.cloud"
            ]

