apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: bidrag
  name: {{ name }}
  namespace: bidrag
spec:
  accessPolicy:
    outbound:
      rules:
        - application: {{ bidrag-testdata-cloud.name }}
        - application: {{ test.name }}
  azure:
    application:
      enabled: true
  env:
    - name: ENVIRONMENT
      value: {{ environment }}
    - name: TEST_NAIS_APP
      value: {{ test.name }}
    - name: TEST_NAIS_APP_INGRESS
      value: {{ test.ingress }}
    - name: TESTDATA_URL
      value: {{ bidrag-testdata-cloud.ingress }}
  image: {{ image }}
  template:
    spec:
      containers:
        - name: {{ name }}
          image: {{ image }}
          command:
            - "mvn"
            - "-f"
            - "/pom.xml"
            - "-Dexec.classpathScope=test"
            - "-Dexec.mainClass=no.nav.bidrag.cucumber.BidragCucumberCloud"
