apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: bidrag
  name: {{ name }}
  namespace: bidrag
spec:
  azure:
    application:
      enabled: true
  env:
    - name: INGRESSES_FOR_TAGS
      value: {{ ingresses-for-tags }}
    - name: SANITY_CHECK
      value: "true"
  envFrom:
    - secret: test-credentials-z992903
  image: {{ image }}
