apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: bidrag
  name: bidrag-cucumber-cloud-scheduled-job
  namespace: bidrag
# todo: start cucmber tests (1. do not use image of nais app and post to deployed nais app, see README.md)
spec:
  command:
    - "curl"
    - "-X"
    - "POST"
    - "http://127.0.0.1:4191/shutdown"
  image: {{ image }}
  schedule: '30 3 0 0 0'
