apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: bidrag
  name: {{ name }}
  namespace: bidrag
spec:
  azure:
    application:
      enabled: true
  env:
    - name: INGRESSES_FOR_TAGS
      value: {{ ingresses-for-tags }}
    - name: SANITY_CHECK
      value: "true" # sanity check until satisfactory settings of TEST_USER and TEST_AUTH
    - name: TEST_USER
      value: {{ test-user }}
    - name: TEST_AUTH
      value: "${{ test-auth }}"
  image: {{ image }}
