management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  servlet:
    context-path: /bidrag-cucumber-cloud

springdoc:
  packages-to-scan: no.nav.bidrag.cucumber.controller

testbrukere:
  identer:
    BISYS_BASIS: Z994977
appscope.clients:
  oppgave: api://${OPPGAVE_SCOPE}/.default
  bidrag-sak: api://${SAK_SCOPE}/.default
  bidrag-beregn-saertilskudd-rest: api://${BEREGN_SAERTILSKUDD_SCOPE}/.default
  bidrag-beregn-forskudd-rest: api://${BEREGN_FORSKUDD_SCOPE}/.default
  bidrag-beregn-barnebidrag-rest: api://${BEREGN_BARNEBIDRAG_SCOPE}/.default
  bidrag-dokument-forsendelse: api://${DOKUMENT_FORSENDELSE_SCOPE}/.default
  bidrag-dokument: api://${BIDRAG_DOKUMENT_SCOPE}/.default
spring:
  application:
    name: bidrag-cucumber-cloud
  main:
    allow-bean-definition-overriding: true
  main.banner-mode: "off"
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      security.protocol: SSL
      ssl:
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        truststore:
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        endpoint.identification.algorithm:
      consumer:
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# Dummy value in order to start local app
TOPIC_JOURNALPOST: bidrag.journalpost
TOPIC_DOKUMENT: bidrag.dokument