management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  servlet:
    context-path: /bidrag-cucumber-cloud

springdoc:
  packages-to-scan: no.nav.bidrag.cucumber.controller

# Dummy value in order to start local app
TOPIC_JOURNALPOST: bidrag.journalpost
