name: build and deploy
on:
  push:
    branches:
      - '**'
      - '!feature/cron-fix'

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
  INGRESS_CUCUMBER: https://bidrag-cucumber-cloud.ekstern.dev.nav.no

jobs:
  build:
    name: Build with maven and docker
    runs-on: ubuntu-latest

    steps:
      - uses: navikt/bidrag-docker/exists@v1
        id: dockerimage
        with:
          image_name: bidrag-cucumber-cloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo NOT_FOUND=${{ steps.dockerimage.outputs.not_found }} >> $GITHUB_ENV
      - uses: actions/checkout@v2
        if: env.NOT_FOUND == 'true'
      - uses: actions/setup-java@v1
        if: env.NOT_FOUND == 'true'
        with:
          java-version: '17'
      - uses: actions/cache@v1
        if: env.NOT_FOUND == 'true'
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: navikt/bidrag-maven/setup@v7
        if: env.NOT_FOUND == 'true'
        with:
          repositories: maven-central=https://repo.maven.apache.org/maven2,github-packages=https://maven.pkg.github.com/navikt/maven-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: navikt/bidrag-maven/verify-dependencies@v7
        if: env.NOT_FOUND == 'true'
      - run: mvn install -B -e
        if: env.NOT_FOUND == 'true'
      - name: Build and publish Docker image
        if: env.NOT_FOUND == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker image build --tag ${IMAGE} .
          echo ${GITHUB_TOKEN} | docker login ghcr.io --username ${GITHUB_REPOSITORY} --password-stdin
          docker image push ${IMAGE}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy bidrag-cucumber-cloud
    needs: build

    steps:
      - uses: actions/checkout@v2
        with:
          path: deploy
      - name: Deploy bidrag-cucumber-cloud testapplication for main branches to dev-gcp
        if: github.ref == 'refs/heads/main'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/.nais/nais.yaml
          VARS: deploy/.nais/main.yaml
      - name: Deploy bidrag-cucumber-cloud testapplication for feature branches to dev-gcp
        if: github.ref != 'refs/heads/main'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/.nais/nais.yaml
          VARS: deploy/.nais/feature.yaml

  run-tests-for-cucumber-cloud:
    runs-on: ubuntu-latest
    name: bidrag-cucumber-cloud
    needs: deploy

    steps:
      - run: echo "INGRESS_CUCUMBER=https://bidrag-cucumber-cloud-feature.ekstern.dev.nav.no" >> $GITHUB_ENV
        if: github.ref != 'refs/heads/main'
      - run: |
          curl -H "Content-Type: application/json" -i \
               --request POST \
               --data '{"ingressesForApps":[
                   "${{ env.INGRESS_CUCUMBER }}@tag:bidrag-cucumber-cloud"
                 ]}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)

  run-tests-for-bidrag-stonad:
    runs-on: ubuntu-latest
    name: bidrag-stonad
    needs: deploy

    env:
      INGRESS_STONAD: https://bidrag-stonad.dev.intern.nav.no

    steps:
      - name: feature ingresses
        if: github.ref != 'refs/heads/main'
        run: |
          echo "INGRESS_STONAD=https://bidrag-stonad-feature.dev.intern.nav.no" >> $GITHUB_ENV
          echo "INGRESS_CUCUMBER=https://bidrag-cucumber-cloud-feature.ekstern.dev.nav.no" >> $GITHUB_ENV
      - run: |
          curl -H "Content-Type: application/json" -i \
               --request POST \
               --data '{"noContextPathForApps":["bidrag-stonad"],"ingressesForApps":[
                   "${{ env.INGRESS_STONAD }}@tag:bidrag-stonad"
                 ]}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)

  run-tests-for-bidrag-vedtak:
    runs-on: ubuntu-latest
    name: bidrag-vedtak
    needs: deploy

    env:
      INGRESS_VEDTAK: https://bidrag-vedtak.dev.intern.nav.no

    steps:
      - name: feature ingresses
        if: github.ref != 'refs/heads/main'
        run: |
          echo "INGRESS_VEDTAK=https://bidrag-vedtak-feature.dev.intern.nav.no" >> $GITHUB_ENV
          echo "INGRESS_CUCUMBER=https://bidrag-cucumber-cloud-feature.ekstern.dev.nav.no" >> $GITHUB_ENV
      - run: |
          curl -H "Content-Type: application/json" -i \
               --request POST \
               --data '{"noContextPathForApps":["bidrag-vedtak"],"ingressesForApps":[
                   "${{ env.INGRESS_VEDTAK }}@tag:bidrag-vedtak"
                 ]}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)

  run-tests-for-bidrag-grunnlag:
    runs-on: ubuntu-latest
    name: bidrag-grunnlag
    needs: deploy

    env:
      INGRESS_GRUNNLAG: https://bidrag-grunnlag.dev.intern.nav.no

    steps:
      - name: feature ingresses
        if: github.ref != 'refs/heads/main'
        run: |
          echo "INGRESS_GRUNNLAG=https://bidrag-grunnlag-feature.dev.intern.nav.no" >> $GITHUB_ENV
          echo "INGRESS_CUCUMBER=https://bidrag-cucumber-cloud-feature.ekstern.dev.nav.no" >> $GITHUB_ENV
      - run: |
          curl -H "Content-Type: application/json" -i \
               --request POST \
               --data '{"noContextPathForApps":["bidrag-grunnlag"],"ingressesForApps":[
                   "${{ env.INGRESS_GRUNNLAG }}@tag:bidrag-grunnlag"
                 ]}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)

  run-tests-for-bidrag-beregn-saertilskudd:
    runs-on: ubuntu-latest
    name: bidrag-beregn-saertilskudd
    needs: deploy

    env:
      INGRESS_BEREGN_SAERTILSKUDD: https://bidrag-beregn-saertilskudd-rest.dev.intern.nav.no

    steps:
      - name: feature ingresses
        if: github.ref != 'refs/heads/main'
        run: |
          echo "INGRESS_BEREGN_SAERTILSKUDD=https://bidrag-beregn-saertilskudd-rest-feature.dev.intern.nav.no" >> $GITHUB_ENV
          echo "INGRESS_CUCUMBER=https://bidrag-cucumber-cloud-feature.ekstern.dev.nav.no" >> $GITHUB_ENV
      - run: |
          curl -H "Content-Type: application/json" -i \
               --request POST \
               --data '{"noContextPathForApps":["bidrag-beregn-saertilskudd-rest"],"ingressesForApps":[
                   "${{ env.INGRESS_BEREGN_SAERTILSKUDD }}@tag:bidrag-beregn-saertilskudd-rest"
                 ], "testUsername":"z992903"}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)

  run-tests-for-bidrag-beregn-forskudd:
    runs-on: ubuntu-latest
    name: bidrag-beregn-forskudd
    needs: deploy

    env:
      INGRESS_BEREGN_FORSKUDD: https://bidrag-beregn-forskudd-rest.dev.intern.nav.no

    steps:
      - name: feature ingresses
        if: github.ref != 'refs/heads/main'
        run: |
          echo "INGRESS_BEREGN_FORSKUDD=https://bidrag-beregn-forskudd-rest-feature.dev.intern.nav.no" >> $GITHUB_ENV
          echo "INGRESS_CUCUMBER=https://bidrag-cucumber-cloud-feature.ekstern.dev.nav.no" >> $GITHUB_ENV
      - run: |
          curl -H "Content-Type: application/json" -i \
               --request POST \
               --data '{"noContextPathForApps":["bidrag-beregn-forskudd-rest"],"ingressesForApps":[
                   "${{ env.INGRESS_BEREGN_FORSKUDD }}@tag:bidrag-beregn-forskudd-rest"
                 ], "testUsername":"z992903"}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)

  run-tests-for-bidrag-beregn-barnebidrag:
    runs-on: ubuntu-latest
    name: bidrag-beregn-barnebidrag
    needs: deploy

    env:
      INGRESS_BEREGN_BARNEBIDRAG: https://bidrag-beregn-barnebidrag-rest.dev.intern.nav.no

    steps:
      - name: feature ingresses
        if: github.ref != 'refs/heads/main'
        run: |
          echo "INGRESS_BEREGN_BARNEBIDRAG=https://bidrag-beregn-barnebidrag-rest-feature.dev.intern.nav.no" >> $GITHUB_ENV
          echo "INGRESS_CUCUMBER=https://bidrag-cucumber-cloud-feature.ekstern.dev.nav.no" >> $GITHUB_ENV
      - run: |
          curl -H "Content-Type: application/json" -i \
               --request POST \
               --data '{"noContextPathForApps":["bidrag-beregn-barnebidrag-rest"],"ingressesForApps":[
                   "${{ env.INGRESS_BEREGN_BARNEBIDRAG }}@tag:bidrag-beregn-barnebidrag-rest"
                 ], "testUsername":"z992903"}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)

  run-tests-for-arbeidsflyt:
    runs-on: ubuntu-latest
    name: bidrag-arbeidsflyt
    needs: deploy

    env:
      INGRESS_OPPGAVE: https://oppgave.dev-fss-pub.nais.io

    steps:
      - name: feature ingresses
        if: github.ref != 'refs/heads/main'
        run: |
          echo "INGRESS_OPPGAVE=https://oppgave-q1.dev-fss-pub.nais.io" >> $GITHUB_ENV
          echo "INGRESS_CUCUMBER=https://bidrag-cucumber-cloud-feature.ekstern.dev.nav.no" >> $GITHUB_ENV
      - name: endre-fagomrade
        run: |
          curl -H "Content-Type: application/json" -i \
               --request POST \
               --data '{"tags":["@arbeidsflyt-endre-fagomrade"],"testUsername":"z992903","noContextPathForApps":["oppgave"],"ingressesForApps":[
                   "${{ env.INGRESS_OPPGAVE }}@oppgave"
                 ]}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - name: journalforing
        run: |
          curl -H "Content-Type: application/json" -i \
               --request POST \
               --data '{"tags":["@arbeidsflyt-journalforing"],"testUsername":"z992903","noContextPathForApps":["oppgave"],"ingressesForApps":[
                   "${{ env.INGRESS_OPPGAVE }}@oppgave"
                 ]}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - name: opprett-oppgave
        run: |
          curl -H "Content-Type: application/json" -i \
               --request POST \
               --data '{"tags":["@arbeidsflyt-opprett-oppgave"],"testUsername":"z992903","noContextPathForApps":["oppgave"],"ingressesForApps":[
                   "${{ env.INGRESS_OPPGAVE }}@oppgave"
                 ]}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - name: overfor-til-annen-enhet
        run: |
          curl -H "Content-Type: application/json" -i \
               --request POST \
               --data '{"tags":["@arbeidsflyt-overfor-til-annen-enhet"],"testUsername":"z992903","noContextPathForApps":["oppgave"],"ingressesForApps":[
                   "${{ env.INGRESS_OPPGAVE }}@oppgave"
                 ]}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)

  bump_dev_version:
    runs-on: ubuntu-latest
    name: Bump SNAPSHOT version
    if: github.ref == 'refs/heads/main'
    needs:
      - run-tests-for-cucumber-cloud
      - run-tests-for-arbeidsflyt
      - run-tests-for-bidrag-stonad
      - run-tests-for-bidrag-vedtak
      - run-tests-for-bidrag-grunnlag
      - run-tests-for-bidrag-beregn-saertilskudd
      - run-tests-for-bidrag-beregn-forskudd
      - run-tests-for-bidrag-beregn-barnebidrag

    steps:
      - uses: actions/checkout@v2
      - uses: navikt/bidrag-git/tag-snap@v1-tag-snap
