name: bump snapshot version
on:
  push:
    branches:
      - main

jobs:

  bump_snapshot_version:
    runs-on: ubuntu-latest
    name: Bump SNAPSHOT version

    steps:
      - uses: actions/checkout@v2
      - uses: navikt/bidrag-git/tag-snap@v1-git-tag-snap
