name: nightly run of cucumber tests
on:
  schedule:
    - cron: '30 2 * * *'

  push:
    branches:
      - feature/cron-fix

env:
  INGRESS_CUCUMBER: https://bidrag-cucumber-cloud.ekstern.dev.nav.no

jobs:

  run-tests-for-cucumber-cloud:
    runs-on: ubuntu-latest
    name: "Run tests: bidrag-cucumber-cloud"

    steps:
      - run: |
          curl -H "Content-Type: application/json" -i \
               --request POST \
               --data '{"ingressesForApps":[
                   "${{ env.INGRESS_CUCUMBER }}@bidrag-cucumber-cloud"
                 ]}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#team-bidrag-dev\", \"username\": \"webhookbot\", \"text\": \"$MELDING\", \"icon_emoji\": \":boom:\"}" $WEBHOOK_URL
        if: ${{ failure() }}
        env:
          MELDING: "<https://github.com/navikt/bidrag-cucumber-cloud/actions|Cucumber tests> for tag @bidrag-cucumber-cloud feilet"
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

  run-tests-for-bidrag-sak:
    runs-on: ubuntu-latest
    name: "Run tests: bidrag-sak"

    env:
      INGRESS_SAK: https://bidrag-sak.dev-fss-pub.nais.io

    steps:
      - run: |
          curl -H "Content-Type: application/json" -i \
               --request POST \
               --data '{"testUsername":"z992903","ingressesForApps":[
                   "${{ env.INGRESS_SAK }}@bidrag-sak"
                 ]}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#team-bidrag-dev\", \"username\": \"webhookbot\", \"text\": \"$MELDING\", \"icon_emoji\": \":boom:\"}" $WEBHOOK_URL
        if: ${{ failure() }}
        env:
          MELDING: "<https://github.com/navikt/bidrag-cucumber-cloud/actions|Cucumber tests> for tag @bidrag-sak feilet"
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

  run-tests-for-bidrag-stonad:
    runs-on: ubuntu-latest
    name: "Run tests: bidrag-stonad"

    env:
      INGRESS_STONAD: https://bidrag-stonad.dev.intern.nav.no

    steps:
      - run: |
          curl -H "Content-Type: application/json" -i \
               --request POST \
               --data '{"ingressesForApps":[
                   "${{ env.INGRESS_STONAD }}@bidrag-stonad"
                 ]}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#team-bidrag-dev\", \"username\": \"webhookbot\", \"text\": \"$MELDING\", \"icon_emoji\": \":boom:\"}" $WEBHOOK_URL
        if: ${{ failure() }}
        env:
          MELDING: "<https://github.com/navikt/bidrag-cucumber-cloud/actions|Cucumber tests> for tab @bidrag-stonad feilet"
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

  run-tests-for-bidrag-vedtak:
    runs-on: ubuntu-latest
    name: "Run tests: bidrag-vedtak"

    env:
      INGRESS_VEDTAK: https://bidrag-vedtak.dev.intern.nav.no

    steps:
      - run: |
          curl -H "Content-Type: application/json" -i \
               --request POST \
               --data '{"ingressesForApps":[
                   "${{ env.INGRESS_VEDTAK }}@bidrag-vedtak"
                 ]}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#team-bidrag-dev\", \"username\": \"webhookbot\", \"text\": \"$MELDING\", \"icon_emoji\": \":boom:\"}" $WEBHOOK_URL
        if: ${{ failure() }}
        env:
          MELDING: "<https://github.com/navikt/bidrag-cucumber-cloud/actions|Cucumber tests> for tag @bidrag-vedtak feilet"
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

  run-tests-for-arbeidsflyt-endre-fagomrade:
    runs-on: ubuntu-latest
    name: "Run tests: arbeidsflyt-endre-fagomrade"

    env:
      INGRESS_OPPGAVE: https://oppgave.dev-fss-pub.nais.io

    steps:
      - run: |
          curl -H "Content-Type: application/json" -i \
               --request POST \
               --data '{"tags":["@arbeidsflyt-endre-fagomrade"],"testUsername":"z992903","noContextPathForApps":["oppgave"],"ingressesForApps":[
                   "${{ env.INGRESS_OPPGAVE }}@no-tag:oppgave"
                 ]}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#team-bidrag-dev\", \"username\": \"webhookbot\", \"text\": \"$MELDING\", \"icon_emoji\": \":boom:\"}" $WEBHOOK_URL
        if: ${{ failure() }}
        env:
          MELDING: "<https://github.com/navikt/bidrag-cucumber-cloud/actions|Cucumber tests> for tag @arbeidsflyt-endre-fagomrade feilet"
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

  run-tests-for-arbeidsflyt-opprett-oppgave:
    runs-on: ubuntu-latest
    name: "Run tests: arbeidsflyt-opprett-oppgave"

    env:
      INGRESS_OPPGAVE: https://oppgave.dev-fss-pub.nais.io

    steps:
      - run: |
          curl -H "Content-Type: application/json" -i \
               --request POST \
               --data '{"tags":["@arbeidsflyt-opprett-oppgave"],"testUsername":"z992903","noContextPathForApps":["oppgave"],"ingressesForApps":[
                   "${{ env.INGRESS_OPPGAVE }}@no-tag:oppgave"
                 ]}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#team-bidrag-dev\", \"username\": \"webhookbot\", \"text\": \"$MELDING\", \"icon_emoji\": \":boom:\"}" $WEBHOOK_URL
        if: ${{ failure() }}
        env:
          MELDING: "<https://github.com/navikt/bidrag-cucumber-cloud/actions|Cucumber tests> for tag @arbeidsflyt-opprett-oppgave feilet"
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

  run-tests-for-bidrag-beregn:
    runs-on: ubuntu-latest
    name: "Run tests: bidrag-beregn-*"

    env:
      INGRESS_BARNEBIDRAG: https://bidrag-beregn-barnebidrag-rest.dev.adeo.no
      INGRESS_FORSKUDD: https://bidrag-beregn-forskudd-rest.dev.adeo.no
      INGRESS_SAERTILSKUDD: https://bidrag-beregn-saertilskudd-rest.dev.adeo.no

    steps:
      - name: feature ingresses
        if: github.ref != 'refs/heads/main'
        run: |
          echo "INGRESS_BARNEBIDRAG=https://bidrag-beregn-barnebidrag-rest-feature.dev.adeo.no" >> $GITHUB_ENV
          echo "INGRESS_CUCUMBER=https://bidrag-cucumber-cloud-feature.ekstern.dev.nav.no" >> $GITHUB_ENV
          echo "INGRESS_FORSKUDD=https://bidrag-beregn-forskudd-rest-feature.dev.adeo.no" >> $GITHUB_ENV
          echo "INGRESS_SAERTILSKUDD=https://bidrag-beregn-saertilskudd-rest-feature.dev.adeo.no" >> $GITHUB_ENV
      - run: |
          curl -H "Content-Type: application/json" -i \
               --request POST \
               --data '{"ingressesForApps":[
                   "${{ env.INGRESS_BARNEBIDRAG }}@bidrag-beregn-barnebidrag-rest",
                   "${{ env.INGRESS_FORSKUDD }}@bidrag-beregn-forskudd-rest",
                   "${{ env.INGRESS_SAERTILSKUDD }}@bidrag-beregn-saertilskudd-rest"
                 ]}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          # cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)
      - run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#team-bidrag-dev\", \"username\": \"webhookbot\", \"text\": \"$MELDING\", \"icon_emoji\": \":boom:\"}" $WEBHOOK_URL
        if: ${{ failure() }}
        env:
          MELDING: "<https://github.com/navikt/bidrag-cucumber-cloud/actions|Cucumber tests> for tags @bidrag-beregn-* feilet"
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
